### ISSUE TITLE
Move Platform Notes to End of Docs

### ISSUE THREAD

**Issue by brishtibheja** [ankitects/anki-manual#222]
I don't think platform notes has to be in the beginning of the doc. There are multiple reasons for this:

1. First, most of it is not of much value to most people. If you already have downloaded the app and simply want a guide for using it the notes aren't useful. If you're using Windows, you might not need the notes for other OS.
2. The Getting Started page has links to Platform Notes, which itself is linked to in the Introductions page.
3. Maintaining a hierarchy is important and we want the most useful things to be in the beginning. Also, if people are like me, they'll read the Manual from the start when they are a new user, primarily because they don't know about the software enough to make decisions about what to read and what to skip.

I think the platform notes pages should be at the end, near Add ons, etc.

**Comment by dae** [comment]
The rationale for the current position: they are installation instructions, and the user can't do anything else until they've installed the app

**Comment by brishtibheja** [comment]
It is just before the Getting Started section which links people to Platform Notes. I expect people to click on the links so moving from here shouldn't be a problem.

**Comment by brishtibheja** [comment]
Dae, I am wondering what is the purpose of this page: [1](https://docs.ankiweb.net/platform/intro.html) 

If there is important information here, I suggest we put it in the first sub-section of getting started. Also, consider this page: [2](https://docs.ankiweb.net/platform/windows/intro.html). This should contain a list of all the subsections of windows section instead of telling the user to use TOC. Thoughts?

**Comment by dae** [comment]
All parent topics need to have text in them, or it causes issues:

https://github.com/ankitects/anki/issues/3005

I don't have particularly strong feelings here, but would prefer if one or two other people chime in and a consensus is formed before we go making changes.

**Comment by brishtibheja** [comment]
@Danika-Dakika Do you have thoughts on this?My vision is, people will move from 'Background' to 'Getting Started' which has the first section as 'Installing & Upgrading' with links to platform notes for each OS. If somebody has already installed the app or don't need that information (e.g. they use AnkiDroid) they would have a much more smoother experience reading the docs.

**Comment by Danika-Dakika** [comment]
I don't think it's reasonable to move the platform notes to the end of the manual. There is a beginning-to-end process flow in the first part of the manual. It's good to maintain that in general, but it is also quite standard to address these sorts of tech issues at the beginning of documentation, before getting into the "fun" stuff. All-in-all, I think it's in the right place. 

For what it's worth, the segment of users who read page-by-page through starting from the beginning of the manual is vanishingly small. 😅 Speaking as someone who did read the manual before I started (I probably clicked "Docs" on the main page before I scrolled down to the downloads section) -- not even I was willing to wade through unnecessary troubleshooting pages for not-my-OS. But, it was easy to click the section header and know what was there, so that when I got to installing, I would know where to turn if things went poorly.

**Comment by brishtibheja** [comment]
> the segment of users who read page-by-page through starting from the beginning of the manual is vanishingly small.

I have strong opinions about this probably because I read page by page. Especially when the topic is complex, and I don't know what should be read and what can be skipped.

I don't think if the pages were written better, this would've been a problem. Right now, if a screen reader user wants to skip this portion he has to go to the sidebar for no reason. I think this part could've been better written.

**Comment by brishtibheja** [comment]
I rewrote the Platform Notes page at #228, suggestions are welcome. There is some duplication of links, but I think it's worth it.
