### ISSUE TITLE
Use Bold Formatting for UI Elements

### ISSUE THREAD

**Issue by brishtibheja** [ankitects/anki-manual#253]
Manual doesn't have a consistent style when it comes to formatting, especially with UI elements where bold, code, quotes and also no formatting has been tried.

I believe we should use bold as most style guides recommend. In particular, [Google's way](https://developers.google.com/style/ui-elements).

**Comment by dae** [comment]
No particular preference here; agree we should be consistent.

**Comment by Danika-Dakika** [comment]
Bold is fine with me. 

I think a minimal style guide would be a good place for us to memorialize decisions like this, and help us move toward consistency with each edit. [I'm emphasizing minimal because I don't think we'll need a ton of guidelines, or to be totally homogenous.] 

Could we start adding things like this to the README? Or maybe a single-page wiki would be better?

**Comment by dae** [comment]
README sounds good - it's the first thing people will see when they click on the GitHub icon at the top of the manual.
